name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - production
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm test
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      EAS_RELEASE_CHANNEL: ${{ github.ref == 'refs/heads/production' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - name: Publish OTA update
        run: npx eas update --non-interactive --channel $EAS_RELEASE_CHANNEL
