name: Mobile Beta Distribution

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build iOS and submit to TestFlight
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          APPLE_APP_ID: ${{ secrets.APPLE_APP_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        run: |
          npx eas build --platform ios --non-interactive --profile preview
          npx eas submit --platform ios --non-interactive \
            --apple-app-id "$APPLE_APP_ID" \
            --team-id "$APPLE_TEAM_ID" \
            --apple-app-specific-password "$APPLE_APP_SPECIFIC_PASSWORD" \
            --group "beta-testers"
      - name: Build Android and submit to Google Play Internal
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          npx eas build --platform android --non-interactive --profile preview
          echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > service-account.json
          npx eas submit --platform android --non-interactive \
            --key-file service-account.json \
            --track internal \
            --group "beta-testers"
      - name: Open feedback issue
        uses: actions/github-script@v8
        with:
          script: |
            const {data: issue} = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Beta feedback for ${context.sha.substring(0,7)}`,
              body: 'Collect tester feedback and bug reports here.',
              labels: ['beta-feedback']
            });
            core.notice(`Feedback issue: ${issue.html_url}`);

  promote:
    needs: build-and-upload
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Release approved. Promote builds in store dashboards."
