name: Prisma Schema Check
on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Prisma format check
        run: pnpm exec prisma format --check

      - name: Prisma validate
        run: pnpm exec prisma validate

      - name: Migration check
        run: pnpm exec prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --exit-code
